#!/bin/bash

echo ''
echo 'This script copies the udev rule to /etc/udev/rules.d/'
echo 'to configure the U2D2 device for the ffw follower.'
echo ''

sudo cp `ros2 pkg prefix ffw_bringup`/share/ffw_bringup/ffw.rules /etc/udev/rules.d/

echo ''
echo 'Reload rules'
echo ''
sudo udevadm control --reload-rules
sudo udevadm trigger
